//imported entire into srm

var alText = {
  title: 'How much are Alabama wetland forests worth?',
  citeKey: 'davis2018',
  otherLink: 'https://www.dogwoodalliance.org/esr/Alabama-State-Fact-Sheet.pdf',
  image: 'https://i.imgur.com/MKr70z3.jpg',
  facts: ['According to the Treasures of the South report, Alabama’s wetland forests are worth $34.4 billion and could increase in value to $36.7 billion by investing in conservation and better management practices. Protection from extreme events alone is worth $10.3 billion to the state. Recreation, tourism, and aesthetics alone is worth $8.7 billion to the state. Water and waste treatment alone is worth $7.9 billion to the state. Food and pollination alone is worth $5 billion to the state. Regulating services alone is worth $2.4 billion to the state. Raw materials alone is worth $59 million to the state. ',
          'Alabama’s Wetland Forests Are Worth $34.3 Billion',
          'Worth could increase up to $2.3 billion',
          'Wetland Forest Gem: Beaverdam Creek Swamp in the Wheeler National Wildlife Refuge',
          'Over two million acres of wetland forest, including ninety six swamps and over six thousand streams',
          'Only four percent of wetland forests in Alabama are permanently protected',
          'Regulating Services: Alabama’s Wetland Forests Provide $2.4 Billion',
          'Value in climate regulation, air quality, soil formation, and erosion control could increase up to $78 million',
          'There are an estimated ninety three million megagrams of carbon stored in Alabama wetland forests',
          'Raw Materials: Alabama’s Wetland Forests Provide $58 Million', 
          'In 2011, there were 115 forest product mills (e.g., pulp and timber) employing over thirteen thousand people in Alabama',  
          'Value in raw materials could increase by up to $58 million',
          'Food and Pollination: Alabama’s Wetland Forests Provide $5 Billion', 
          'Value in food and pollination could increase up to $340 million', 
          'Alabama wetland forests provide habitat for pollinators of agricultural crops', 
          'Nearly seven hundred and fifty thousand residents in Alabama hunt or fish', 
          'In 2016, hunters purchased two hundred thousand deer hunting licenses', 
          'In 2016, hunters harvested over a hundred thousand ducks and geese within Alabama',
          'Protection From Extreme Events: Alabama’s Wetland Forests Provide $10.3 Billion', 
          'Value in protection from extreme events and water flow regulation could increase up to $660 million', 
          'Three flood events caused over a billion each in damages since 1980', 
          'Six major hurricanes (larger than category two) and sixteen minor hurricanes made landfall on the Alabama coastline between 1851-2004',
          'Water Supply and Waste Treatment: Alabama’s Wetland Forests Provide $7.9 Billion', 
          'Value in water supply and waste treatment could increase up to $540 million', 
          'More than half of Alabama residents rely on public sewer systems', 
          'Many public facilities rely on natural infrastructure to reduce costs of waste and water treatment', 
          'Over ten percent of Alabama residents rely on private water sources like wells', 
          'Residents rely on forests to naturally filter pollutants from their water supply',
          'Aesthetics, Tourism, and Recreation: Alabama’s Wetland Forests Provide $8.7 Billion',
          'Value in aesthetics and recreation could increase up to $610 million ',
          'Alabama had nearly twenty six million visitors in 2016, who spent $13.3 billion and supported one hundred and eighty thousand tourism jobs',
          'Roughly half of Alabama residents participate in wildlife-related recreation, and they spent $2.7 billion in 2011 alone'], 
};

var arText = {
  title: 'How much are Arkansas wetland forests worth?', 
  citeKey: 'davis2018',
  otherLink:'https://www.dogwoodalliance.org/esr/Arkansas-State-Fact-Sheet.pdf',
  image: 'https://i.imgur.com/NRUNfwo.jpg', 
  facts: ['Arkansas’ Wetland Forests Are Worth $37.4 Billion',
          'Worth could increase up to $2.8 billion ',
          'Wetland Forest Gem: Seven Devils Swamp',
          'Two and a half million acres of wetland forest, including nearly two hundred swamps and over four thousand streams 1',
          'Eighteen percent of wetland forests in Arkansas are in permanent protection',
          'Protection From Extreme Events: Arkansas’ Wetland Forests Provide $11.2 Billion',
          'Value in protection from extreme events and water flow regulation could increase up to $830 million ',
          'Seven flood events caused over a billion each of damages since 1980 2',
          'Since 1851, there have been fourteen major Mississippi river floods, impacting states along the river like Arkansas 3',
          'Aesthetics, Tourism, and Recreation: Arkansas’ Wetland Forests Provide $9.4 Billion',
          'Value in aesthetics and recreation could increase up to $760 million',
          'Arkansas had over twenty nine million visitors in 2016, who spent $7.7 billion and supported over one hundred thousand tourism jobs 4',
          'Over sixty percent of Arkansas residents participated in wildlife-related recreation, spending $1.8 billion in 2011 5',
          'Water Supply and Waste Treatment: Arkansas’ Wetland Forests Provide $8.6 Billion',
          'Value in water supply and waste treatment could increase up to $690 million ',
          'More than sixty percent of Arkansas residents rely on public sewer systems ',
          'Many public facilities rely on natural infrastructure to reduce costs of waste and water treatment 6',
          'Nearly twenty percent of Arkansas residents rely on private water sources like wells. ',
          'Residents rely on forests to naturally filter pollutants from their water supply 6',
          'Food and Pollination: Arkansas’ Wetland Forests Provide $5.4 Billion',
          'Value in food and pollination could increase up to $430 million',
          'Arkansas wetland forests provide habitat for pollinators of agricultural crops.',
          'Over five hundred and fifty thousand residents in Arkansas hunt or fish 5',
          'In 2016, hunters purchased three hundred thousand deer hunting licenses 7',
          'In 2016, hunters harvested over a hundred thousand ducks and geese within Arkansas 8',
          'Regulating Services: Arkansas’ Wetland Forests Provide $2.7 Billion',
          'Value in climate regulation, air quality, soil formation, and erosion control could increase up to $96 million',
          'There are an estimated 105 million megagrams of carbon stored in Arkansas wetland forests',
          'Continual carbon storage reduces the worst impacts of climate change',
          'Raw Materials: Arkansas’ Wetland Forests Provide $86 Million',
          'In 2011, there were ninety five forest product mills (e.g., pulp and timber) employing over nine thousand people in Arkansas 9  ',
          'Value in raw materials could increase by up to $40 million',], 
          
          };
          
          var flText = {
          title: 'How much are Florida wetland forests worth?',
          image: 'https://i.imgur.com/2lr6VVH.jpg',
          citeKey: 'davis2018',
          otherLink:'https://www.dogwoodalliance.org/esr/Florida-State-Fact-Sheet.pdf',
          
          facts: ['Florida’s Wetland Forests Are Worth $80.8 Billion',
          'Worth could increase up to $7.5 billion ',
          'Wetland Forest Gem: Okefenokee Swamp, a swamp that straddles the Georgia-Florida line',
          'Over five million acres of wetland forest, including over a thousand named swamps and nearly three thousand named streams in the state 1',
          'Twelve percent of wetland forests in Florida are in permanent protection',
          'Protection From Extreme Events: Florida’s Wetland Forests Provide $24.2 Billion',
          'Value in protection from extreme events and water flow regulation could increase up to $2.1 billion ',
          'One flood event caused over four billion dollars of damages in 1982 2',
          'Between 1851 and 2004, thirty five major hurricanes (categories 3-5) made landfall on the Florida coastline 3',
          'Aesthetics, Tourism, and Recreation: Florida’s Wetland Forests Provide $20.2 Billion',
          'Value in aesthetics and recreation could increase up to $2.1 billion',
          'Florida had 112 million visitors in 2016, who spent $108.8 billion in and supported 1.4 million tourism jobs 4',
          'Nearly forty percent of Florida residents participated in wildlife-related recreation, spending $9 billion in 2011 5',
          'Water Supply and Waste Treatment: Florida’s Wetland Forests Provide $18.6 Billion',
          'Value in water supply and waste treatment could increase up to $1.8 billion ',
          'More than seventy percent of Florida residents rely on public sewer systems',
          'Many public facilities rely on natural infrastructure to reduce costs of waste and water treatment 6',
          'Over ten percent of Florida residents rely on private water sources like wells',
          'Residents rely on forests to naturally filter pollutants from their water supply 6',
          'Food and Pollination: Florida’s Wetland Forests Provide $11.7 Billion',
          'Value in food and pollination could increase up to $1.1 billion',
          'Florida wetland forests provide habitat for pollinators of agricultural crops',
          'Over two million residents in Florida hunt or fish 5',
          'In 2016, hunters purchased over a hundred thousand deer hunting licenses 7',
          'In 2016, hunters harvested nearly two hundred thousand ducks and geese within Florida 8',
          'Regulating Services: Florida’s Wetland Forests Provide $5.9 Billion',
          'Value in climate regulation, air quality, soil formation, and erosion control could increase up to $265 million',
          'There are an estimated 291 million megagrams of carbon stored in Florida wetland forests',
          'Continual carbon storage reduces the worst impacts of climate change',
          'Raw Materials: Florida’s Wetland Forests Provide $167 Million',
          'In 2011, there were fifty two forest product mills (e.g., pulp and timber) employing over six thousand people in Florida 9 ',
          'Value in raw materials could increase up to $108 million',
         ], 
  
};

var gaText = {
  title: 'How much are Georgia wetland forests worth?',
  
  citeKey: 'davis2018',
  otherLink: 'https://www.dogwoodalliance.org/esr/Florida-State-Fact-Sheet.pdf',
  image: 'https://i.imgur.com/rtU0Ypr.jpg',
  facts: ['Georgia’s Wetland Forests Are Worth $67.3 Billion',
          'Worth could increase up to $2.8 billion ',
          'Wetland Forest Gem: Okefenokee Swamp, a swamp that straddles the Georgia-Florida line',
          'Georgia has over four million acres of wetland forest, including nearly five hundred named swamps and over five thousand named streams in the state 1',
          'Nine percent of Georgia wetland forests are permanently protected',
          'Protection From Extreme Events: Georgia’s Wetland Forests Provide $20.1 Billion',
          'Value in protection from extreme events and water flow regulation could increase up to $740 million ',
          'Two flood events with over a billion dollars of damages since 1980 2',
          'Between 1851 and 2004, three major hurricanes (categories 3-5) made landfall on the Georgia coastline 3',
          'Aesthetics, Tourism, and Recreation: Georgia’s Wetland Forests Provide $16.9 Billion',
          'Value in aesthetics and recreation could increase up to $860 million',
          'Georgia had sixty million visitors in 2011, which contributed $61.1 billion in visitor spending and supported 439,000 tourism jobs 4–6',
          'Over forty percent of Georgia residents participated in wildlife-related recreation, spending $4.6 billion in 2011 7',
          'Water Supply and Waste Treatment: Georgia’s Wetland Forests Provide $15.5 Billion',
          'Value in water supply and waste treatment could increase up to $640 million ',
          'More than sixty percent of Georgia residents rely on public sewer systems',
          'Many public facilities rely on natural infrastructure to reduce costs of waste and water treatment 8',
          'Nearly twenty percent of Georgia residents rely on private water sources like wells',
          'Residents rely on forests to naturally filter pollutants from their water supply 8',
          'Food and Pollination: Georgia’s Wetland Forests Provide $9.8 Billion',
          'Value in food and pollination could increase up to $390 million',
          'Georgia wetland forests provide habitat for pollinators of agricultural crops.',
          'Nearly a million residents in Georgia hunt or fish 7',
          'In 2016, hunters purchased  over three hundred thousand deer hunting licenses 9',
          'In 2016, hunters harvested over two hundred thousand ducks and geese within Georgia 10',
          'Regulating Services: Georgia’s Wetland Forests Provide $4.8 Billion',
          'Value in climate regulation, air quality, soil formation, and erosion control could increase up to $107 million',
          'There are an estimated 258 million megagrams of carbon stored in the state’s wetland forests',
          'Continual carbon storage reduces the worst impacts of climate change',
          'Raw Materials: Georgia’s Wetland Forests Provide $122 Million',
          'In 2011, there were 151 forest product mills (e.g., pulp and timber) employing over thirteen thousand people in the state 11 ',
          'Value in raw materials could increase up to $57 million',
         ], 
          
          };
          
    var kyText = {
          title: 'How much are Kentucky wetland forests worth?',
          image: 'https://i.imgur.com/8iwb73A.jpg',
          citeKey: 'davis2018',
          otherLink:'https://www.dogwoodalliance.org/esr/Florida-State-Fact-Sheet.pdf',
          
          facts: ['Kentucky’s Wetland Forests Are Worth $1.9 Billion',
          'Worth could increase up to $500 million ',
          'Wetland Forest Gem: Cypress Creek Swamp, one of the best remaining examples of a bottomland hardwood forest',
          'Kentucky has one hundred and eighty thousand acres of wetland forest, including twenty seven named swamps and over eleven thousand named streams in the state',
          'Nine percent of Kentucky wetland forests are permanently protected',
          'Protection From Extreme Events: Kentucky’s Wetland Forests Provide $570 Million',
          'Value in protection from extreme events and water flow regulation could increase up to $140 million ',
          'Two flood events caused over a billion dollars each of damages since 1980',
          'Since 1851, there have been fourteen major Mississippi river floods, impacting states along the river like Kentucky ',
          'Aesthetics, Tourism, and Recreation: Kentucky’s Wetland Forests Provide $460 Million',
          'Value in aesthetics and recreation could increase up to $130 million ',
          'Kentucky had sixty million visitors in 2011, who spent $9.2 billion and supported nearly two hundred thousand tourism jobs.',
          'Almost sixty percent of residents participated in wildlife-related recreation, spending $2.9 billion in 2011',
          'Water Supply and Waste Treatment: Kentucky’s Wetland Forests Provide $430 Million',
          'Value in water supply and waste treatment could increase up to $120 million ',
          'Almost sixty percent of Kentucky residents rely on public sewer systems',
          'Many public facilities rely on natural infrastructure to reduce costs of waste and water treatment',
          'Nearly twenty percent of Kentucky residents rely on private water sources like wells',
          'Residents rely on forests to naturally filter pollutants from their water supply',
          'Food and Pollination: Kentucky’s Wetland Forests Provide $270 Million',
          'Value in food and pollination could increase up to $80 million ',
          'Kentucky wetland forests provide habitat for pollinators of agricultural crops',
          'Over six hundred thousand residents in the state hunt or fish ',
          'In 2016, hunters purchased nearly two hundred thousand deer hunting licenses',
          'In 2016, hunters harvested over one hundred and fifty thousand ducks and geese within the state',
          'Regulating Services: Kentucky’s Wetland Forests Provide $169 Million',
          'Value in climate regulation, air quality, soil formation, and erosion control could increase up to $16 million',
          'There are an estimated six million megagrams of carbon stored in the state’s wetland forests',
          'Continual carbon storage reduces the worst impacts of climate change',
          'Raw Materials: Kentucky’s Wetland Forests Provide $14 Million',
          'In 2011, there were 225 forest product mills (e.g., pulp and timber) employing over four thousand people in the state',
         ], 
  
};

var laText = {
  title: 'How much are Louisiana wetland forests worth?',
  image: 'https://i.imgur.com/eNdhBv4.jpg',
  citeKey: 'davis2018',
  otherLink:'https://www.dogwoodalliance.org/esr/Florida-State-Fact-Sheet.pdf',
  
  facts: ['Louisiana’s Wetland Forests Are Worth $79 Billion',
          'Worth could increase up to $6.5 billion ',
          'Wetland Forest Gem: Atchafalaya Swamp, the largest wetland and swamp in the United States',
          'Over five million acres of wetland forest, including nearly three hundred named swamps and over four thousand named streams in the state',
          'Only five percent of Louisiana wetland forests are permanently protected',
          'Protection From Extreme Events: Louisiana’s Wetland Forests Provide $23.8 Billion',
          'Value in protection from extreme events and water flow regulation could increase up to $1.9 billion ',
          'Eight flood events amassed over a billion dollars of damages each since 1980',
          'Since 1851, there have been fourteen major Mississippi river floods, impacting states along the river like Louisiana ',
          'Between 1851 and 2004, eighteen major hurricanes (categories 3-5) made landfall on the Louisiana coastline ',
          'Aesthetics, Tourism, and Recreation: Louisiana’s Wetland Forests Provide $20 billion',
          'Value in aesthetics and recreation could increase up to $1.7 million',
          'Louisiana had nearly thirty million visitors in 2015, who spent $11.5 billion and supported over one hundred and seventy thousand tourism jobs',
          'Almost half of residents participated in wildlife-related recreation, spending $2.2 billion in 2011 ',
          'Water Supply and Waste Treatment: Louisiana’s Wetland Forests Provide $18.3 Billion',
          'Value in water supply and waste treatment could increase up to $1.6 billion ',
          'More than seventy percent of residents rely on public sewer systems',
          'Many public facilities rely on natural infrastructure to reduce costs of waste and water treatment ',
          'Over ten percent of residents rely on private water sources like wells',
          'Residents rely on forests to naturally filter pollutants from their water supply ',
          'Food and Pollination: Louisiana’s Wetland Forests Provide $11.5 Billion',
          'Value in food and pollination could increase up to $1 billion',
          'Wetland forests provide habitat for pollinators of agricultural crops',
          'Over eight hundred thousand residents in the state hunt or fish ',
          'In 2016, hunters purchased nearly two hundred thousand deer hunting licenses ',
          'In 2016, hunters harvested almost a million ducks and geese within the state ',
          'Regulating Services: Louisiana’s Wetland Forests Provide $5.73 Billion',
          'Value in climate regulation, air quality, soil formation, and erosion control could increase up to $218 million',
          'There are an estimated 214 million megagrams of carbon stored in the state’s wetland forests',
          'Continual carbon storage reduces the worst impacts of climate change',
          'Raw Materials: Louisiana’s Wetland Forests Provide $170 Million',
          'In 2011, there were forty forest product mills (e.g., pulp and timber) employing over seven thousand people in the state  ',
          'Value in raw materials could increase up to $129 million',
         ], 
          
          };
          
          var moText = {
          title: 'How much are Missouri wetland forests worth?',
          image: 'https://i.imgur.com/s7rbOSv.jpg',
          citeKey: 'davis2018',
          otherLink:'https://www.dogwoodalliance.org/esr/Florida-State-Fact-Sheet.pdf',
          
          facts: ['Missouri’s Wetland Forests Are Worth $7.7 Billion',
          'Worth could increase up to $1.3 billion ',
          'Wetland Forest Gem: Mingo National Wildlife Refuge',
          'Nearly seven hundred thousand acres of wetland forest, including twenty four named swamps and over five thousand named streams in the state 1',
          'Fifteen percent of Missouri wetland forests are permanently protected',
          'Protection From Extreme Events: Missouri’s Wetland Forests Provide $2.3 Billion',
          'Value in protection from extreme events and water flow regulation could increase up to $370 million ',
          'Six flood events amassed over a billion dollars of damages each since 1980 2',
          'Since 1851, there have been fourteen major Mississippi river floods, impacting states along the river like Missouri 3 ',
          'Aesthetics, Tourism, and Recreation: Missouri’s Wetland Forests Provide $1.9 billion',
          'Value in aesthetics and recreation could increase up to $340 million  ',
          'Missouri had forty two million visitors in 2016, which contributed $13.1 billion in visitor spending and supported over three hundred thousand tourism jobs 4',
          'Nearly sixty percent of residents participated in wildlife-related recreation, spending $2.7 billion in 2011 5',
          'Water Supply and Waste Treatment: Missouri’s Wetland Forests Provide $1.7 Billion',
          'Value in water supply and waste treatment could increase up to $310 million ',
          'More than seventy percent of residents rely on public sewer systems',
          'Many public facilities rely on natural infrastructure to reduce costs of waste and water treatment 6',
          'Almost twenty percent of residents rely on private water sources like wells',
          'Residents rely on forests to naturally filter pollutants from their water supply 6',
          'Food and Pollination: Missouri’s Wetland Forests Provide $1.1 Billion',
          'Value in food and pollination could increase up to $190 million',
          'Wetland forests provide habitat for pollinators of agricultural crops',
          'Over a million residents in the state hunt or fish 5',
          'In 2016, hunters purchased over five hundred thousand deer hunting licenses 7',
          'In 2016, hunters harvested over five hundred thousand ducks and geese within the state 8',
          'Regulating Services: Missouri’s Wetland Forests Provide $664 Million',
          'Value in climate regulation, air quality, soil formation, and erosion control could increase up to $42 million',
          'There are an estimated seventeen million megagrams of carbon stored in the state’s wetland forests',
          'Continual carbon storage reduces the worst impacts of climate change',
          'Raw Materials: Missouri’s Wetland Forests Provide $49 Million',
          'Value in raw materials could increase up to $1 million',
         ], 
  
};            


var msText = {
  title: 'How much are Mississippi wetland forests worth?',
  image: 'https://i.imgur.com/LIR7BRy.jpg',
  citeKey: 'davis2018',
  otherLink:'https://www.dogwoodalliance.org/esr/Florida-State-Fact-Sheet.pdf',
  
  facts: ['Mississippi’s Wetland Forests Are Worth $51 Billion',
          'Worth could increase up to $4.2 billion, but only five percent of wetland forests in Mississippi are permanently protected',
          'Wetland Forest Gem: Noxubee National Wildlife Refuge',
          'Three and a half million acres of wetland forest, including over one hundred named swamps and over four thousand named streams in the state 1',
          'Protection From Extreme Events: Mississippi’s Wetland Forests Provide $15.3 Billion',
          'Value in protection from extreme events and water flow regulation could increase up to $1.2 billion',
          'Five flood events amassing over a billion dollars in damages each since 1980 2',
          'Since 1851, there have been fourteen major Mississippi river floods, impacting states along the river like Mississippi 3 ',
          'Between 1851 and 2004, eight major hurricanes (categories 3-5) made landfall on the Mississippi coastline 4 ',
          'Aesthetics, Tourism, and Recreation: Mississippi’s Wetland Forests Provide $12.8 billion',
          'Value in aesthetics and recreation could increase up to $1.1 billion',
          'Mississippi had twenty three million visitors in 2016, which contributed $6.3 billion in visitor spending and supported over eighty thousand tourism jobs 5',
          'Nearly sixty percent of residents participated in wildlife-related recreation, spending $2.6 billion in 2011 6',
          'Water Supply and Waste Treatment: Mississippi’s Wetland Forests Provide $11.7 Billion',
          'Value in water supply and waste treatment could increase up to $1 billion',
          'Almost sixty percent of residents rely on public sewer systems',
          'Many public facilities rely on natural infrastructure to reduce costs of waste and water treatment 7',
          'Over ten percent of residents rely on private water sources like wells',
          'Residents rely on forests to naturally filter pollutants from their water supply 7',
          'Food and Pollination: Mississippi’s Wetland Forests Provide $7.4 Billion',
          'Value in food and pollination could increase up to $630 million',
          'Wetland forests provide habitat for pollinators of agricultural crops',
          'Approximately seven hundred thousand residents in the state hunt or fish 6',
          'In 2016, hunters purchased nearly two hundred thousand deer hunting licenses 8',
          'In 2016, hunters harvested nearly two hundred and fifty thousand ducks and geese within the state 9',
          'Regulating Services: Mississippi’s Wetland Forests Provide $3.8 Billion',
          'Value in climate regulation, air quality, soil formation, and erosion control could increase up to $143 million',
          'There are an estimated 140 million megagrams of carbon stored in the state’s wetland forests',
          'Continual carbon storage reduces the worst impacts of climate change',
          'Raw Materials: Mississippi’s Wetland Forests Provide $129 Million',
          'In 2011, there were sixty three forest product mills (e.g., pulp and timber) employing over seven thousand people in the state 10 ',
          'Value in raw materials could increase up to $78 million',
         ], 
          
          };
          
          
          
          var ncText = {
          title: 'How much are North Carolina wetland forests worth?',
          image: 'https://i.imgur.com/OV3PJ4i.jpg',
          citeKey: 'davis2018',
          otherLink:'https://www.dogwoodalliance.org/esr/Florida-State-Fact-Sheet.pdf',
          
          facts: [
          'North Carolina’s Wetland Forests Are Worth $27 Billion',
          'Worth could increase up to $5.1 billion',
          'Wetland Forest Gem: Green Swamp in southeastern North Carolina',
          'Over two million acres of wetland forest, including over five hundred named swamps and over nine thousand named streams in the state 1',
          'Just seven percent of wetland forests in North Carolina are permanently protected',
          'Protection From Extreme Events: North Carolina’s Wetland Forests Provide $8 Billion',
          'Value in protection from extreme events and water flow regulation could increase up to $1.5 billion',
          'One flood event cost over a billion dollars of damages since 1980 2',
          'Between 1851 and 2004, twelve major hurricanes (categories 3-5) made landfall on the North Carolina coastline 3 ',
          'Aesthetics, Tourism, and Recreation: North Carolina’s Wetland Forests Provide $6.6 billion',
          'Value in aesthetics and recreation could increase up to $1.4 billion ',
          'North Carolina had over fifty million visitors in 2015, who spent $21.9 billion and supported over two hundred thousand tourism jobs 4',
          'Nearly half of residents participated in wildlife-related recreation, spending $3.3 billion in 2011 5',
          'Water Supply and Waste Treatment: North Carolina’s Wetland Forests Provide $6 Billion',
          'Value in water supply and waste treatment could increase up to $1.2 billion',
          'Half of residents rely on public sewer systems',
          'Many public facilities rely on natural infrastructure to reduce costs of waste and water treatment 6',
          'Over a third of residents rely on private water sources like wells',
          'Residents rely on forests to naturally filter pollutants from their water supply 6',
          'Food and Pollination: North Carolina’s Wetland Forests Provide $3.8 Billion',
          'Value in food and pollination could increase up to $780 million ',
          'Wetland forests provide habitat for pollinators of agricultural crops ',
          'Over a million residents in the state hunt or fish 5',
          'In 2016, hunters purchased two hundred and fifty thousand deer hunting licenses 7',
          'In 2016, hunters harvested over five hundred thousand ducks and geese within the state 8',
          'Regulating Services: North Carolina’s Wetland Forests Provide $2.3 Billion',
          'Value in climate regulation, air quality, soil formation, and erosion control could increase up to $178 million',
          'There are an estimated 134 million megagrams of carbon stored in the state’s wetland forests',
          'Continual carbon storage reduces the worst impacts of climate change ',
          'Raw Materials: North Carolina’s Wetland Forests Provide $171 Million',
          'In 2011, there were 135 forest product mills (e.g., pulp and timber) employing over nine thousand people in the state 9 ',
          'Value in raw materials  could increase up to $6 million',
         ], 
  
};


var okText = {
  title: 'How much are Oklahoma wetland forests worth?',
  image: 'https://i.imgur.com/vosKYQR.jpg',
  citeKey: 'davis2018',
  otherLink: 'https://www.dogwoodalliance.org/esr/Florida-State-Fact-Sheet.pdf',
  
  facts: ['Oklahoma’s Wetland Forests Are Worth $1.7 Billion',
          'Worth could increase up to $118 million',
          'Wetland Forest Gem: Little River National Wildlife Refuge',
          'One hundred and sixty thousand acres of wetland forest, including seven named swamps and over three thousand named streams in the state 1',
          'Nineteen percent of wetland forests in Oklahoma are permanently protected',
          'Protection From Extreme Events: Oklahoma’s Wetland Forests Provide $517 Million',
          'Value in protection from extreme events and water flow regulation could increase up to $34 million',
          'Eighteen major flood events hit four gulf states, including Oklahoma, between March of 2015 and August of 2016 2',
          'Four flood events cost over a billion dollars of damages each since 1980 3',
          'Aesthetics, Tourism, and Recreation: Oklahoma’s Wetland Forests Provide $420 Million',
          'Value in aesthetics and recreation could increase up to $32 million ',
          'Oklahoma had over twenty five million visitors in 2010, who spent $6.2 billion in and supported over seventy thousand tourism jobs 4',
          'Over two-thirds of residents participated in wildlife-related recreation, spending $1.8 billion in 2011 5',
          'Water Supply and Waste Treatment: Oklahoma’s Wetland Forests Provide $385 Million',
          'Value in water supply and waste treatment could increase up to $29 million',
          'Over half of residents rely on public sewer systems',
          'Many public facilities rely on natural infrastructure to reduce costs of waste and water treatment 6',
          'Over ten percent of residents rely on private water sources like wells ',
          'Residents rely on forests to naturally filter pollutants from their water supply 6',
          'Food and Pollination: Oklahoma’s Wetland Forests Provide $243 Million',
          'Value in food and pollination could increase up to $17 million',
          'Wetland forests provide habitat for pollinators of agricultural crops',
          'Nearly eight hundred thousand residents in the state hunt or fish 5',
          'In 2016, hunters purchased two hundred thousand deer hunting licenses 7',
          'In 2016, hunters harvested over three hundred thousand ducks and geese within the state 8',
          'Regulating Services: Oklahoma’s Wetland Forests Provide $149 Million',
          'Value in climate regulation, air quality, soil formation, and erosion control could increase up to $5 million ',
          'There are an estimated four million megagrams of carbon stored in the state’s wetland forests',
          'Continual carbon storage reduces the worst impacts of climate change',
          'Raw Materials: Oklahoma’s  Wetland Forests Provide $11 Million',
          'In 2011, there were thirteen forest product mills (e.g., pulp and timber) employing almost a thousand people in the state 9 ',
          'Value in raw materials could increase by up to $1 million',
         ], 
          
          };
          
          
          var scText = {
          title: 'How much are South Carolina wetland forests worth?',
          image: 'https://i.imgur.com/XKX0PLM.jpg',
          citeKey: 'davis2018',
          otherLink:'https://www.dogwoodalliance.org/esr/Florida-State-Fact-Sheet.pdf',
          
          facts: ['South Carolina’s Wetland Forests Are Worth $39.6 Billion',
          'Worth could increase up to $5.1 billion ',
          'Wetland Forest Gem: Congaree National Park, the largest tract of old growth bottomland hardwood forest',
          'Just over three million acres of wetland forest, including five hundred named swamps and over three thousand named streams in the state 1',
          'Only five percent of wetland forests in South Carolina are permanently protected',
          'Protection From Extreme Events: South Carolina’s Wetland Forests Provide $11.9 Billion',
          'Value in protection from extreme events and water flow regulation could increase up to $1.5 billion ',
          'Two flood events cost over a billion dollars in damages each since 1980 2',
          'Between 1851 and 2004, 31 hurricanes and 6 major hurricanes (categories 3-5) made landfall on the North Carolina coastline 3 ',
          'Aesthetics, Tourism, and Recreation: South Carolina’s Wetland Forests Provide $9.8 billion',
          'Value in aesthetics and recreation could increase up to $1.4 billion',
          'South Carolina had thirty million visitors in 2015, which contributed $20.2 billion in visitor spending and supported around two hundred thousand tourism jobs 4',
          'Nearly half of residents participated in wildlife-related recreation, spending $2 billion in 2011 5',
          'Water Supply and Waste Treatment: South Carolina’s Wetland Forests Provide $9 Billion',
          'Value in water supply and waste treatment could increase up to $1.2 billion ',
          'Over half of residents rely on public sewer systems',
          'Many public facilities rely on natural infrastructure to reduce costs of waste and water treatment 6',
          'Over twenty percent of residents rely on private water sources like wells',
          'Residents rely on forests to naturally filter pollutants from their water supply 6',
          'Food and Pollination: South Carolina’s Wetland Forests Provide $5.7 Billion',
          'Value in food and pollination could increase up to $760 million',
          'Wetland forests provide habitat for pollinators of agricultural crops',
          'Over six hundred thousand residents in the state hunt or fish 5',
          'In 2016, hunters purchased nearly a hundred and fifty thousand deer hunting licenses 7',
          'In 2016, hunters harvested over a hundred and fifty thousand ducks and geese within the state 8',
          'Regulating Services: South Carolina’s Wetland Forests Provide $3.2 Billion',
          'Value in climate regulation, air quality, soil formation, and erosion control could increase up to $180 million',
          'There are an estimated 187 million megagrams of carbon stored in the state’s wetland forests',
          'Continual carbon storage reduces the worst impacts of climate change.',
          'Raw Materials: South Carolina’s Wetland Forests Provide $180 Million',
          'In 2011, there were seventy forest product mills (e.g., pulp and timber) employing over eight thousand people in the state 9 ',
          'Value in raw materials could increase by up to $26 million',
         ], 
  
};


var tnText = {
  title: 'How much are Tennessee wetland forests worth?',
  image: 'https://i.imgur.com/rar84g0.jpg',
  citeKey: 'davis2018',
  otherLink:'https://www.dogwoodalliance.org/esr/Florida-State-Fact-Sheet.pdf',
  
  facts: ['Tennessee’s Wetland Forests Are Worth $7.8 Billion',
          'Worth could increase up to $924 million',
          'Wetland Forest Gem: Chickasaw National Wildlife Refuge',
          'Over six hundred thousand acres of wetland forest, including forty one named swamps and almost ten thousand named streams in the state 1',
          'Seventeen percent of wetland forests in Tennessee are permanently protected',
          'Protection From Extreme Events: Tennessee’s Wetland Forests Provide $2.3 Billion',
          'Value in protection from extreme events and water flow regulation could increase up to $270 million',
          'Since 1851, there have been fourteen major Mississippi river floods, impacting states along the river like Tennessee 2',
          'Three flood events cost over a billion dollars of damages each since 1980 3',
          'Aesthetics, Tourism, and Recreation: Tennessee’s Wetland Forests Provide $1.9 Million',
          'Value in aesthetics and recreation could increase up to $254 million ',
          'Tennessee had over a hundred million visitors in 2014, which contributed $18.4 billion in visitor spending and supported over one hundred and fifty thousand tourism jobs 4',
          'Over half of residents participated in wildlife-related recreation, spending $2.9 billion in 2011 5',
          'Water Supply and Waste Treatment: Tennessee’s Wetland Forests Provide $1.8 Billion',
          'Value in water supply and waste treatment could increase up to $223 million',
          'Over three-fourths of residents rely on public sewer systems',
          'Many public facilities rely on natural infrastructure to reduce costs of waste and water treatment 6',
          'Over ten percent of residents rely on private water sources like wells',
          'Residents rely on forests to naturally filter pollutants from their water supply 6',
          'Food and Pollination: Tennessee’s Wetland Forests Provide $1.1 Billion',
          'Value in food and pollination could increase up to $141 million',
          'Wetland forests provide habitat for pollinators of agricultural crops',
          'Over nine hundred thousand residents in the state hunt or fish 5',
          'In 2016, hunters purchased two hundred and fifty thousand deer hunting licenses 7',
          'In 2016, hunters harvested over two hundred thousand ducks and geese within the state 8',
          'Regulating Services: Tennessee’s Wetland Forests Provide $629 Million',
          'Value in climate regulation, air quality, soil formation, and erosion control could increase up to $32 million ',
          'There are an estimated twenty four million megagrams of carbon stored in the state’s wetland forests',
          'Continual carbon storage reduces the worst impacts of climate change',
          'Raw Materials: Tennessee’s Wetland Forests Provide $36 Million',
          'In 2011, there were 254 forest product mills (e.g., pulp and timber) employing nearly five thousand people in the state 9 ',
          'Value in raw materials could increase up to $4 million',
         ], 
          
          };
          
          
          
          var txText = {
          title: 'How much are Texas wetland forests worth?',
          image: 'https://i.imgur.com/9tpCgct.jpg',
          citeKey: 'davis2018',
          otherLink:'https://www.dogwoodalliance.org/esr/Florida-State-Fact-Sheet.pdf',
          
          facts: ['Texas’ Wetland Forests Are Worth $53.9 Billion',
          'Worth could increase up to $4.9 billion',
          'Wetland Forest Gem: McFaddin National Wildlife Refuge',
          'Nearly four million acres of wetland forest, including two hundred and four named swamps and over eleven thousand named streams in the state 1',
          'Only four percent of Texas wetland forests are permanently protected',
          'Protection From Extreme Events: Texas’ Wetland Forests Provide $16.1 Billion',
          'Value in protection from extreme events and water flow regulation could increase up to $1.4 billion',
          'Seven flood events amassing over a billion dollars in damages each since 1980 2',
          'Eighteen major flood events hit four gulf states, including Texas, between March of 2015 and August of 2016 3',
          'Between 1851 and 2004, nineteen major hurricanes (categories 3-5) made landfall on the Texas coastline 4',
          'Aesthetics, Tourism, and Recreation: Texas’ Wetland Forests Provide $13.5 billion',
          'Value in aesthetics and recreation could increase up to $1.3 billion',
          'Texas had over two hundred million visitors in 2015, who spent $69.1 billion and supported five hundred thousand tourism jobs 5,6',
          'Nearly forty percent of residents participated in wildlife-related recreation, spending $6.2 billion in 2011 7',
          'Water Supply and Waste Treatment: Texas’ Wetland Forests Provide $12.3 Billion',
          'Value in water supply and waste treatment could increase up to $1.2 billion',
          'More than two thirds of residents rely on public sewer systems',
          'Many public facilities rely on natural infrastructure to reduce costs of waste and water treatment 8',
          'Less than ten percent of residents rely on private water sources like wells',
          'Residents rely on forests to naturally filter pollutants from their water supply 8',
          'Food and Pollination: Texas’ Wetland Forests Provide $7.8 Billion',
          'Value in food and pollination could increase up to $739 million ',
          'Wetland forests provide habitat for pollinators of agricultural crops ',
          'Nearly three million residents in the state hunt or fish 7',
          'In 2016, hunters purchased over a million deer hunting licenses 9',
          'In 2016, hunters harvested over one million ducks and geese within the state 10',
          'Regulating Services: Texas’ Wetland Forests Provide $4 Billion',
          'Value in climate regulation, air quality, soil formation, and erosion control could increase up to $165 million',
          'There are an estimated 121 million megagrams of carbon stored in the state’s wetland forests',
          'Continual carbon storage reduces the worst impacts of climate change',
          'Raw Materials: Texas’ Wetland Forests Provide $148 Million',
          'In 2011, there were sixty nine forest product mills (e.g., pulp and timber) employing 4,878 people in the state 11 ',
          'Value in raw materials could increase by up to $79 million',
         ], 
  
};



var vaText = {
  title: 'How much are Virginia wetland forests worth?',
  image: 'https://i.imgur.com/qSZCkmV.jpg',
  citeKey: 'davis2018',
  otherLink:'https://www.dogwoodalliance.org/esr/Florida-State-Fact-Sheet.pdf',
  
  facts: ['Virginia’s Wetland Forests Are Worth $13.9 Billion',
          'Worth could increase up to $1.3 billion',
          'Wetland Forest Gem: The iconic Dismal Swamp that straddles the border between Virginia and North Carolina',
          'Over nine hundred thousand acres of wetland forest, including one hundred and fifty named swamps and over seven thousand named streams in the state 1',
          'Only seven percent of wetland forests in Virginia are permanently protected',
          'Protection From Extreme Events: Virginia’s Wetland Forests Provide $4.2 Billion',
          'Value in protection from extreme events and water flow regulation could increase up to $340 million',
          'Three flood events amassing over a billion dollars in damages each since 1980 2',
          'Between 1851 and 2004, twelve hurricanes made landfall on the Virginia coastline 3',
          'Aesthetics, Tourism, and Recreation: Virginia’s Wetland Forests Provide $3.5 billion',
          'Value in aesthetics and recreation could increase up to $388 million ',
          'Virginia had forty five million visitors in 2016, who spent $23.7 billion and supported over two hundred thousand tourism jobs 4,5',
          'Nearly half of residents participated in wildlife-related recreation, spending $3.5 billion in 2011 6',
          'Water Supply and Waste Treatment: Virginia’s Wetland Forests Provide $3.2 Billion',
          'Value in water supply and waste treatment could increase up to $292 million',
          'More than two thirds of residents rely on public sewer systems',
          'Many public facilities rely on natural infrastructure to reduce costs of waste and water treatment 7',
          'Over twenty percent of residents rely on private water sources like wells',
          'Residents rely on forests to naturally filter pollutants from their water supply 7',
          'Food and Pollination: Virginia’s Wetland Forests Provide $2 Billion',
          'Value in food and pollination could increase up to $178 million ',
          'Wetland forests provide habitat for pollinators of agricultural crops ',
          'Approximately eight hundred and fifty thousand residents in the state hunt or fish 6',
          'In 2016, hunters purchased nearly a hundred thousand deer hunting licenses 8',
          'In 2016, hunters harvested over two hundred thousand ducks and geese within the state 9',
          'Regulating Services: Virginia’s Wetland Forests Provide $1 Billion',
          'Value in climate regulation, air quality, soil formation, and erosion control could increase up to $48 million ',
          'There are an estimated forty seven million megagrams of carbon stored in the state’s wetland forests',
          'Continual carbon storage reduces the worst impacts of climate change ',
          'Raw Materials: Virginia’s Wetland Forests Provide $31 Million',
          'In 2011, there were 123 forest product mills (e.g., pulp and timber) employing over seven thousand people in the state 10 ',
          'Value in raw materials could increase by up to $15 million',
         ], 
          
          };